application: matrufsc2
version: 1
module: default
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1h"
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: automatic 
  max_pending_latency: 30ms
  max_concurrent_requests: 80

builtins:
- appstats: on

handlers:
- url: /js
  static_dir: frontend/public/js
  http_headers:
    #Cache-Control: private
    Cache-Control: public, max-age=3600
    Pragma: cache

- url: /css
  static_dir: frontend/public/css
  http_headers:
    #Cache-Control: private
    Cache-Control: public, max-age=3600
    Pragma: cache

- url: /font
  static_dir: frontend/public/font
  http_headers:
    #Cache-Control: private
    Cache-Control: public, max-age=3600
    Pragma: cache

- url: /api/.*
  script: matrufsc2.app

- url: /secret/update/
  script: matrufsc2.app
  login: admin

- url: /.*
  static_files: frontend/views/index-optimize.html
  upload: frontend/views/index-optimize.html
  http_headers:
    Cache-Control: public, max-age=3600
    Pragma: cache
